// CopyShell.idl : CopyShell 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(CopyShell.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(87056417-6195-40C2-8E3B-B02D3EE57378),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface ICopyMenu : IDispatch{
};
[
    uuid(198AA953-3756-4853-8B18-64398874DD88),
    version(1.0),
]
library CopyShellLib
{
    importlib("stdole2.tlb");
    [
        uuid(786C8A4B-9492-47C2-982D-74CECD921E74), // <<<<<
        helpstring("ComponentRegister Class")
    ]
    coclass CopyMenu
    {
        [default] interface ICopyMenu;
    };
};
