// CopyPathMenu.idl : IDL source for CopyPathMenu
//

// This file will be processed by the MIDL tool to
// produce the type library (CopyPathMenu.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(51f75cdd-a09c-4f67-9113-afa9628aecf5),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICopyPathMenuImpl : IDispatch
{
};
[
	uuid(bc4b0323-3734-441f-8a5a-aeb4d4dd51d8),
	version(1.0),
]
library CopyPathMenuLib
{
	importlib("stdole2.tlb");
	[
		uuid(7a73e28f-7fd5-436e-bdc0-8f25fb8ede0f)
	]
	coclass CopyPathMenuImpl
	{
		[default] interface ICopyPathMenuImpl;
	};
};

import "shobjidl.idl";
